version: '3.9'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  authorizer:
    image: lakhansamani/authorizer:1.1.0
    ports:
      - 8080
    depends_on:
      - redis
    environment:
      - ENV=production
      - DATABASE_TYPE=sqlite
      - DATABASE_URL=data.db
      - REDIS_URL=redis://redis:6379
  nginx:
    container_name: nginx
    image: nginx:1.21-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
    depends_on:
      - authorizer
